### ISSUE TITLE
Wrong License in README.md

### ISSUE THREAD

**Issue by Albert0011** [UBC-MDS/heart_disease_predictor_py#18]
Hi guys, just noticed that the license written in README.md is MIT License, which was supposed to be CC0 because that is what we are using in this project!

**Comment by Arc-Celt** [comment]
Oh yeah. Can we directly change that in the main branch? Or fix it on another branch and merge it later? (the latest branch should be the introduction branch)

**Comment by Albert0011** [comment]
I fixed in in the latest pull request, can you check ?

**Comment by Arc-Celt** [comment]
Checked 1 hour ago
