### ISSUE TITLE
Milestone 1: To-do list and work breakdown

### ISSUE THREAD

**Issue by stephqwu** [UBC-MDS/heart_disease_predictor_py#20]
Title
Summary - Albert
Introduction - Stephanie
provide some relevant background information on the topic so that someone unfamiliar with it will be prepared to understand the rest of your report
clearly state the question you tried to answer with your project
identify and describe the dataset that was used to answer the question
Methods & Results: 
describe in written english the methods you used to perform your analysis from beginning to end that narrates the code the does the analysis.
your report should include code which:
loads data from the original source on the web - Stephanie
wrangles and cleans the data from it’s original (downloaded) format to the format necessary for the planned classification or clustering analysis - Stephanie
performs a summary of the data set that is relevant for exploratory data analysis related to the planned classification analysis - Ziyuan
creates a visualization of the dataset that is relevant for exploratory data analysis related to the planned classification analysis - Ziyuan
performs classification or regression analysis - Albert
performs classification or regression analysis - Archer
creates a visualization of the result of the analysis - Albert & Archer
note: all tables and figure should have a figure/table number and a legend
Discussion: - Archer
summarize what you found
discuss whether this is what you expected to find?
discuss what impact could such findings have?
discuss what future questions could this lead to?
References: - Ziyuan & Stephanie
at least 4 citations relevant to the project (format is your choose, just be consistent across the references).

**Comment by Arc-Celt** [comment]
11.21 Created the CODE_OF_CONDUCT.md file.

11.22 Performed classification using Decision Tree and Logistic Regression Model. Fine tuned models and compared results. Picked the best model to score on the test data, and drew a visualization of feature coefficients. Discuss the results.
