### ISSUE TITLE
2. Set up a docker container locally

### ISSUE THREAD

**Issue by Arc-Celt** [UBC-MDS/heart_disease_predictor_py#23]
Base Docker Image: quay.io/jupyter/minimal-notebook:afe30f0c9ad8. 
Follow the environment.yml > conda-linux-64.lock > Dockerfile workflow in individual assignment 2 to pin the version of the software added.

**Comment by stephqwu** [comment]
Ready for review https://github.com/UBC-MDS/heart_disease_predictor_py/pull/32/
