### ISSUE TITLE
How to do the Correct data file format item on the Data validation checklist

### ISSUE THREAD

**Issue by stephqwu** [UBC-MDS/heart_disease_predictor_py#37]
I asked Sky and Tiffany about this in class. The way to do this is with python (not pandora) to check the data file format for correctness.

**Comment by Albert0011** [comment]
do you mean pandera? didn't tiffany taught us with pandera?

**Comment by stephqwu** [comment]
yes pandera (autocorrect) 

they recommended checking Correct data file format with python so I will figure out how to do it that way instead

**Comment by stephqwu** [comment]
Closing because answered https://github.com/UBC-MDS/heart_disease_predictor_py/pull/39
