### ISSUE TITLE
(Optional) Add a step to docker-publish.yml to update the tag automatically

### ISSUE THREAD

**Issue by Arc-Celt** [UBC-MDS/heart_disease_predictor_py#42]
Tiffany provided a great approach of updating the docker-compose.yml file with the tag of the new image that is built and published on Slack.

>  If you want to add a step to your docker-publish.yml workflow so that it automatically updates the docker-compose.yml file with the tag of the new image that is built and published, you can add these two steps at the very end of your docker-publish.yml workflow file. Make sure to replace the two occurrences of ttimbers/dsci522-dockerfile-practice-tt with your docker image name. Also, for this to work, in your GitHub repo you need to go to Settings > Actions > General > under "Workflow permissions" make sure read and write permissions are enabled.

See code here: https://ubc-mds.slack.com/archives/C24HUNRJL/p1732820716697419

**Comment by Albert0011** [comment]
Are you working on it? I can fix that one

**Comment by Albert0011** [comment]
Done !
