### ISSUE TITLE
For the rest of the checks, would it also be easier to not use pandera?

### ISSUE THREAD

**Issue by stephqwu** [UBC-MDS/heart_disease_predictor_py#44]
I'm curious about your opinions😄

**Comment by Arc-Celt** [comment]
I think both are fine? But I'm not sure if using Panderia will make our data validation more readable and interpretable.
One thing is for sure, I'm gonna stick to deep checks for my part——it’ll be much easier! 😸

**Comment by stephqwu** [comment]
It sounds like I can approve the PR as it is since it looks like everyone will do their part how they see fit, this is the first I'm hearing of deep checks though. If you need me to do anything for you to be able to use it please feel free to raise it to my attention in a separate issue

**Comment by Albert0011** [comment]
I think pandera looks pretty clean to me, as long as everyone can understand the code it should be fine with me.

**Comment by stephqwu** [comment]
I agree about that part, closing because we are now officially deciding to use pandera and Cheryl has told me she is working on it

**Comment by cherylziunzhao** [comment]
All checks have been added as per the feedback. Let me know if there are any additional tweaks needed before merging.
